### ISSUE TITLE
决赛数据集

### ISSUE THREAD

**Issue by zhaoerchao** [shenweichen/Tencent_Social_Ads2017_Mobile_App_pCVR#1]
您好, 由于错过了竞赛, 没能下载决赛数据集, 目前想针对它进行一些实验研究. 您能够提供一份决赛数据集吗? 万分感谢~
邮箱 ec_zhao@126.com

**Comment by shenweichen** [comment]
@zhaoerchao 决赛数据集链接 http://spabigdata-1253211098.cosgz.myqcloud.com/final.zip
